name: 'default'

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  security-events: 'write' # security-sast_codeql
  contents: 'write' # delivery-release
  pull-requests: 'write' # tests-test_all (coverage report comment)
  checks: 'write' # tests-test_all (test results annotations)

jobs:
  default:
    uses: 'rios0rios0/pipelines/.github/workflows/yarn-library.yaml@main'
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
